// Code generated by go-gendb, DO NOT EDIT.
// go-gendb version: 0.3
// source: samples/mgo-orm/item.go
package item

import bson "gopkg.in/mgo.v2/bson"

const (
	BaseFieldID         = "_id"
	BaseFieldGpid       = "gpid"
	BaseFieldParentGpid = "parent_gpid"
	BaseFieldInSale     = "in_sale"
	BaseFieldAttrs      = "attrs"
)

const BaseSortIDDesc = "-_id"

type Base struct {
	ID         bson.ObjectId `bson:"_id,omitempty" json:"id"`
	Gpid       int64         `bson:"gpid" json:"gpid"`
	ParentGpid int64         `bson:"parent_gpid" json:"parent_gpid"`
	InSale     bool          `bson:"in_sale" json:"in_sale"`
	Attrs      []*SkuAttr    `bson:"attrs" json:"attrs"`
}