-- ------------------------------------------------------------
-- This file is auto generated by go-gendb mock tools.
-- go-gendb version: 0.1.6
-- Source file: samples/mock/user.toml
-- Create date: 2021-02-01 10:57:10
-- Epoch: 20
-- Num of sql: 40
-- Please create the database first before executing this file.
-- ------------------------------------------------------------

-- epoch: 1
INSERT INTO `user`(`id`,`name`,`age`,`phone`,`email`,`password`) VALUES (100,'IZHjxMkiMocked',47,'136195807457','m4s5BC@qq.cn','DKU3EN3UG0ZIQRPM');
INSERT INTO `user_detail`(`text`,`user_id`) VALUES ('hello',100);

-- epoch: 2
INSERT INTO `user`(`id`,`name`,`age`,`phone`,`email`,`password`) VALUES (101,'aafZCdIMocked',23,'180260936660','xyh1nU@163.com','TV4F3OQLJVR0PKEB');
INSERT INTO `user_detail`(`text`,`user_id`) VALUES ('hello',101);

-- epoch: 3
INSERT INTO `user`(`id`,`name`,`age`,`phone`,`email`,`password`) VALUES (102,'cjUpWXBMocked',33,'137717518942','upssXq@126.cn','1DZ6P2MYWAKX5H4P');
INSERT INTO `user_detail`(`text`,`user_id`) VALUES ('hello',102);

-- epoch: 4
INSERT INTO `user`(`id`,`name`,`age`,`phone`,`email`,`password`) VALUES (106,'fyRrTWMocked',40,'137594208049','me2rb@126.cn','VSQWFNIZSJ5QX4PA');
INSERT INTO `user_detail`(`text`,`user_id`) VALUES ('hello',106);

-- epoch: 5
INSERT INTO `user`(`id`,`name`,`age`,`phone`,`email`,`password`) VALUES (103,'pPaMzgCjaMocked',47,'136591720064','qJsIW@gmail.com','US0EBTBHBT1GPUNN');
INSERT INTO `user_detail`(`text`,`user_id`) VALUES ('hello',103);

-- epoch: 6
INSERT INTO `user`(`id`,`name`,`age`,`phone`,`email`,`password`) VALUES (105,'anHHCFMocked',29,'180227383340','v3zqW@126.com','8UK6BGGFN2UM2SUH');
INSERT INTO `user_detail`(`text`,`user_id`) VALUES ('hello',105);

-- epoch: 7
INSERT INTO `user`(`id`,`name`,`age`,`phone`,`email`,`password`) VALUES (104,'IUeAzMocked',48,'137744565830','58gMH@gmail.com','3RJL1MYR5FH662R0');
INSERT INTO `user_detail`(`text`,`user_id`) VALUES ('hello',104);

-- epoch: 8
INSERT INTO `user`(`id`,`name`,`age`,`phone`,`email`,`password`) VALUES (107,'DfhUnMocked',21,'180645121436','ow8lW@163.cn','AKE2ZV5G99JK95F2');
INSERT INTO `user_detail`(`text`,`user_id`) VALUES ('hello',107);

-- epoch: 9
INSERT INTO `user`(`id`,`name`,`age`,`phone`,`email`,`password`) VALUES (108,'LoHncppXoMocked',30,'180715973108','yGP9Z@gmail.cn','H91RBN8GQWIE84ZU');
INSERT INTO `user_detail`(`text`,`user_id`) VALUES ('hello',108);

-- epoch: 10
INSERT INTO `user`(`id`,`name`,`age`,`phone`,`email`,`password`) VALUES (109,'IvsGjpUMocked',22,'136715667093','zZbUQ@gmail.cn','BQZW423ZY3FFDUI8');
INSERT INTO `user_detail`(`text`,`user_id`) VALUES ('hello',109);

-- epoch: 11
INSERT INTO `user`(`id`,`name`,`age`,`phone`,`email`,`password`) VALUES (114,'VtXefMfMocked',26,'139516043050','kHsKo@qq.com','Q6QRSP93Y6L3Y3O4');
INSERT INTO `user_detail`(`text`,`user_id`) VALUES ('hello',114);

-- epoch: 12
INSERT INTO `user`(`id`,`name`,`age`,`phone`,`email`,`password`) VALUES (119,'AqpfkMocked',20,'137253966655','l0rWq1@gmail.cn','PNS0EF8NG0WJCS32');
INSERT INTO `user_detail`(`text`,`user_id`) VALUES ('hello',119);

-- epoch: 13
INSERT INTO `user`(`id`,`name`,`age`,`phone`,`email`,`password`) VALUES (118,'LqzpXMocked',46,'180901146262','riH9H@gmail.com','XGXYKCQKRPJYBQH4');
INSERT INTO `user_detail`(`text`,`user_id`) VALUES ('hello',118);

-- epoch: 14
INSERT INTO `user`(`id`,`name`,`age`,`phone`,`email`,`password`) VALUES (117,'AcWPjIZMocked',30,'139535427757','glX5OK@163.cn','QAXB8QE53XI4YVJY');
INSERT INTO `user_detail`(`text`,`user_id`) VALUES ('hello',117);

-- epoch: 15
INSERT INTO `user`(`id`,`name`,`age`,`phone`,`email`,`password`) VALUES (110,'fqCEidMocked',27,'136396261553','2kDPop@gmail.com','Q265PB90SV3YUUM3');
INSERT INTO `user_detail`(`text`,`user_id`) VALUES ('hello',110);

-- epoch: 16
INSERT INTO `user`(`id`,`name`,`age`,`phone`,`email`,`password`) VALUES (113,'fmsDlIJQMocked',35,'180218639745','xNOI3@gmail.cn','CBA2YBPHKBOEWBJ5');
INSERT INTO `user_detail`(`text`,`user_id`) VALUES ('hello',113);

-- epoch: 17
INSERT INTO `user`(`id`,`name`,`age`,`phone`,`email`,`password`) VALUES (112,'GIrtXfOMocked',44,'137964108611','of285d@qq.com','9NINPBV39337MBD5');
INSERT INTO `user_detail`(`text`,`user_id`) VALUES ('hello',112);

-- epoch: 18
INSERT INTO `user`(`id`,`name`,`age`,`phone`,`email`,`password`) VALUES (111,'ePjPfDSWKMocked',39,'180884876196','zwpz2@gmail.com','94VEWYE7E9D05JFP');
INSERT INTO `user_detail`(`text`,`user_id`) VALUES ('hello',111);

-- epoch: 19
INSERT INTO `user`(`id`,`name`,`age`,`phone`,`email`,`password`) VALUES (115,'eOUtVAYAaMocked',44,'180248441446','s8mJNr@gmail.cn','TA2VFMDOF8VI88PC');
INSERT INTO `user_detail`(`text`,`user_id`) VALUES ('hello',115);

-- epoch: 20
INSERT INTO `user`(`id`,`name`,`age`,`phone`,`email`,`password`) VALUES (116,'TqttJoexMocked',45,'136034763109','fBFWi@163.com','37SM6B3LWFTRXW9P');
INSERT INTO `user_detail`(`text`,`user_id`) VALUES ('hello',116);
