package help

const CleanUsage = "clean <path>"

const Clean = `
Scan the directory and delete the code files generated by
go-gendb. This will delete all go files with prefix
"zz_generated".

** Warning **
If you use other code generators, and the codes they generate
are also in this format, this command will be deleted by mistake.
Please use it under safe conditions.

See alse: gen, clean-cache`
