// Code generated by go-gendb, DO NOT EDIT.
// go-gendb version: 0.3
// source: samples/quick-start/user.go
package user

import (
	sql "database/sql"
	fmt "fmt"
)

const (
	_UserOper_FindById = "SELECT id, name, age, FROM user WHERE id=?"
	_UserOper_Add      = "INSERT INTO user(id, name, age) VALUES (?, ?, ?)"
)

var UserOper = &_UserOper{}

type _UserOper struct {}

func (*_UserOper) FindById(db *sql.DB, id int64) (*User, error) {
	var a int
}

func (*_UserOper) Add(db *sql.DB, u *User) (sql.Result, error) {
	var a int
}