// Code generated by go-gendb, DO NOT EDIT.
// go-gendb version: 0.3
// source: samples/complicated-sql/oper.go
package db

import (
	run "github.com/fioncat/go-gendb/api/sql/run"
	sql "database/sql"
)

// all sql statement(s) to use
const _LangOper_GetLangs = "SELECT code, languages_id Id FROM languages WHERE code IN ('en', 'cn', 'tw', 'th');"

var LangOper = &_LangOper{}

// Lang is a struct auto generated by LangOper.GetLangs
type Lang struct {
	Code string `table:"languages" field:"code"`
	Id   int32  `table:"languages" field:"languages_id"`
}

type _LangOper struct {}

func (*_LangOper) GetLangs() ([]*Lang, error) {
	var os []*Lang
	err := run.QueryMany(getDB(), _LangOper_GetLangs, nil, nil, func(rows *sql.Rows) error {
		o := new(Lang)
		err := rows.Scan(&o.Code, &o.Id)
		if err != nil {
			return err
		}
		os = append(os, o)
		return nil
	})
	return os, err
}