// +gendb mysql

package user

import "database/sql"

type User struct {

	// generate tags for struct "UserORM"
	// +gendb-struct user
	// +gendb-ignore is_delete
	// +gendb-type is_admin bool

	// UserORM will be automatically generated, it includes the
	// fields in the table user. The field name will be
	// automatically converted to Hump form (Id, Name, IsAdmin, etc.), and
	// the type will be automatically inferred based on the database type.
	// There are some additional configurations. The "ignore" option
	// means to ignore the is_delete field.
	// The "type" option manually specifies the GO type of a field.
	UserORM
}

// This tag indicates that an implementation structure will be generated
// for interface UserDB. The sql statement will be read from "user.sql" in
// the current directory.
// +gendb-inter user.sql

// UserDB defines some operation methods of the user table.
// The specific implementation of these methods is automatically
// generated by gendb. Their sql statements are defined in
// external sql files.
type UserDB interface {
	Add(db *sql.DB, u *User) (int64, error)
	Update(db *sql.DB, u *User) (int64, error)
	FindByID(db *sql.DB, id int64) (*User, error)
	FindByName(db *sql.DB, name string) ([]*User, error)
	Search(db *sql.DB, where string, offset int32, limit int32) ([]*User, error)
	Count(db *sql.DB, where string) (int64, error)
}
