// Code generated by go-gendb. DO NOT EDIT.
// go-gendb version: 0.0.1
// source: examples/user/user.db.go
package user

import (
	time "time"
)

// userORM
type userORM struct {
	// Id 用户id
	Id int64 `table:"user" field:"id"`
	// Name 用户名
	Name string `table:"user" field:"name"`
	// Email 用户邮箱
	Email string `table:"user" field:"email"`
	// Phone 用户电话
	Phone string `table:"user" field:"phone"`
	// Age 用户年龄
	Age int32 `table:"user" field:"age"`
	// CreateTime 创建时间
	CreateTime time.Time `table:"user" field:"create_time"`
	// Password 用户密码
	Password string `table:"user" field:"password"`
	// IsAdmin 是否是管理员 0-不是  1-是
	IsAdmin bool `table:"user" field:"is_admin"`
}

