// Code generated by go-gendb, DO NOT EDIT.
// go-gendb version: 0.3
// source: samples/orm-sql/user_orm.go
package user

import (
	sql "database/sql"
	run "github.com/fioncat/go-gendb/api/sql/run"
)

const (
	UserIdField         = "id"
	UserNameField       = "name"
	UserPhoneField      = "phone"
	UserCodeField       = "code"
	UserIsDeleteField   = "is_removed"
	UserCreateDateField = "create_date"
)

const (
	_User_InsertOne   = "INSERT INTO `user`(`name`,`phone`,`code`,`is_removed`,`create_date`) VALUES (?,?,?,?,?,?)"
	_User_InsertBatch = "INSERT INTO `user`(`name`,`phone`,`code`,`is_removed`,`create_date`) VALUES %s"
	_User_FindById    = "SELECT `id`,`name`,`phone`,`code`,`is_removed`,`create_date` FROM `user` WHERE `id`=?"
	_User_DeleteById  = "DELETE FROM `user` WHERE `id`=?"
	_User_UpdateById  = "UPDATE `user` SET `name`=?,`phone`=?,`code`=?,`is_removed`=?,`create_date`=? WHERE `id`=?"
	_User_Count       = "SELECT COUNT(1) FROM `user`"
)

const _User_FindOneByCode = "SELECT `id`,`name`,`phone`,`code`,`is_removed`,`create_date` FROM `user` WHERE `code`=?"

var UserOper = &_UserOper{}

type _UserOper struct {}

// User 用户表
type User struct {
	Id         int64  `field:"id"`
	Name       string `field:"name"`
	Phone      string `field:"phone"`
	Code       string `field:"code"`
	IsDelete   bool   `field:"is_removed"`
	CreateDate int64  `field:"create_date"`
}