// Code generated by go-gendb. DO NOT EDIT.
// go-gendb version: 0.1.4
// source: samples/quickstart/oper.go
package user

// User is an auto-generated return type for UserDb.FindById
type User struct {
	// Age 用户年龄
	Age int32 `table:"user" field:"age"`
	// CreateTime 创建时间
	CreateTime string `table:"user" field:"create_time"`
	// Email 用户邮箱
	Email string `table:"user" field:"email"`
	// Id 用户id
	Id int64 `table:"user" field:"id"`
	// IsAdmin 是否是管理员 0-不是  1-是
	IsAdmin int32 `table:"user" field:"is_admin"`
	// IsDelete
	IsDelete int32 `table:"user" field:"is_delete"`
	// Name 用户名
	Name string `table:"user" field:"name"`
	// Password 用户密码
	Password string `table:"user" field:"password"`
	// Phone 用户电话
	Phone string `table:"user" field:"phone"`
}

